// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Bootstrap():Promise<app.BootstrapData>;

export function HideWindow():Promise<void>;

export function QuitApp():Promise<void>;

export function SetLocale(arg1:string):Promise<app.BootstrapData>;

export function ShowWindow():Promise<void>;
