// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SetLocale(arg1) {
  return window['go']['main']['App']['SetLocale'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
